import { useState } from 'react'
import type { DemoCallStatus, DemoConversationLink } from '../../types/jobfreeCommunications'
import type { UiContext } from '../../types/domain'
import { authorizeDemoCommunication } from '../../mocks/jobfreeCommunicationsAdapter'
export function DemoCallScreen({ link, role, onBack }: { link?: DemoConversationLink; role: UiContext; onBack: () => void }) {
  const [status, setStatus] = useState<DemoCallStatus>('idle')
  const access = link ? authorizeDemoCommunication({ role, conversationRole: link.role, requestId: link.requestId, jobId: link.jobId, assignmentId: link.assignmentId, assignmentStatus: link.assignmentStatus, scenario: link.scenario, action: 'call' }) : { allowed: false, readOnly: false, reason: 'Không có assignment demo được liên kết.' }
  return <main className="demo-call-screen"><button className="e2-back" type="button" onClick={onBack}>‹ Quay lại</button><span className="e2-demo-tag">CUỘC GỌI DEMO · KHÔNG KẾT NỐI THẬT</span><span className="demo-call-avatar">{link?.participantInitials ?? '?'}</span><h1>{link?.participantName ?? 'Không khả dụng'}</h1><p>{link?.jobTitle} · {link?.assignmentId}</p><strong role="status">{access.allowed ? status === 'idle' ? 'Sẵn sàng mô phỏng' : status === 'dialing_demo' ? 'Đang gọi demo…' : status === 'connecting_demo' ? 'Đang kết nối demo…' : status === 'connected_demo' ? 'Đã kết nối demo (giao diện)' : 'Cuộc gọi demo đã kết thúc' : access.reason}</strong><p className="e2-disclaimer">Không dùng microphone, số điện thoại, WebRTC, Zalo API hoặc telephony. Trạng thái chỉ đổi trong giao diện này.</p>{access.allowed && <div className="demo-call-actions">{(status === 'idle' || status === 'ended') ? <button type="button" onClick={() => { setStatus('dialing_demo'); window.setTimeout(() => setStatus('connecting_demo'), 300); window.setTimeout(() => setStatus('connected_demo'), 700) }}>Bắt đầu demo</button> : <button type="button" className="is-end" onClick={() => setStatus('ended')}>Kết thúc demo</button>}</div>}</main>
}
