import type { Destination } from '../../types/domain'
import type { EmployerDemoProfile } from '../../types/employerAccount'
import type { ReactNode } from 'react'
const sections: { title: string; items: { label: string; note: string; destination: Destination; icon: string }[] }[] = [
  { title: 'HỒ SƠ & QUẢN LÝ', items: [{ label: 'Hồ sơ cá nhân', note: 'Thông tin hiển thị demo', destination: 'employerProfileEdit', icon: 'profile' }, { label: 'Địa chỉ của tôi', note: 'Quản lý địa điểm đã lưu', destination: 'employerAddresses', icon: 'pin' }, { label: 'Thanh toán demo', note: 'Thông tin, không liên kết tài khoản', destination: 'employerPaymentsInfo', icon: 'wallet' }, { label: 'Thông báo', note: 'Cập nhật gắn với yêu cầu demo', destination: 'employerNotifications', icon: 'bell' }] },
  { title: 'HOẠT ĐỘNG DỊCH VỤ', items: [{ label: 'Lịch sử công việc', note: 'Yêu cầu và trạng thái', destination: 'history', icon: 'list' }, { label: 'Đặt lại dịch vụ', note: 'Tạo bản nháp mới từ yêu cầu cũ', destination: 'employerRebook', icon: 'refresh' }, { label: 'Tin nhắn công việc', note: 'Liên hệ theo assignment demo', destination: 'history', icon: 'chat' }, { label: 'Đánh giá đã gửi', note: 'Lịch sử chỉ đọc', destination: 'employerReviews', icon: 'star' }, { label: 'Phản ánh và tranh chấp', note: 'Case demo và timeline', destination: 'employerCases', icon: 'case' }] },
  { title: 'TRỢ GIÚP & CÀI ĐẶT', items: [{ label: 'Trung tâm trợ giúp', note: 'Hướng dẫn các luồng JobFree', destination: 'employerSupport', icon: 'help' }, { label: 'Quyền riêng tư', note: 'Thông tin demo', destination: 'employerPrivacy', icon: 'shield' }, { label: 'Điều khoản sử dụng', note: 'Thông tin demo', destination: 'employerTerms', icon: 'document' }, { label: 'Cài đặt thông báo', note: 'Tuỳ chọn trong phiên', destination: 'employerNotificationSettings', icon: 'settings' }, { label: 'Thông tin ứng dụng', note: 'JobFree Zalo Mini App', destination: 'employerAppInfo', icon: 'info' }] },
]
const iconShape: Record<string, ReactNode> = { profile: <><circle cx="12" cy="8" r="3.5"/><path d="M4.5 20a7.5 7.5 0 0 1 15 0"/></>, pin: <><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/></>, wallet: <><rect x="3.5" y="6" width="17" height="14" rx="2.5"/><path d="M4 8V5.5A2.5 2.5 0 0 1 6.5 3H18M15 13h5.5"/><circle cx="15" cy="13" r=".7"/></>, bell: <><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4"/></>, list: <><rect x="4" y="4" width="16" height="17" rx="2"/><path d="M8 9h8M8 13h8M8 17h5"/></>, refresh: <><path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 9a7 7 0 0 1 12-2l2 2M4 15l2 2a7 7 0 0 0 12-2"/></>, chat: <><path d="M20 11.5a7.5 7.5 0 0 1-8 7.5 9 9 0 0 1-4-.9L4 20l1.2-3.5A7 7 0 0 1 4 12c0-4.2 3.6-7.5 8-7.5s8 2.8 8 7Z"/><path d="M8 11h8M8 14h5"/></>, star: <path d="m12 3 2.7 5.6 6.2.9-4.5 4.4 1.1 6.2-5.5-2.9-5.5 2.9 1.1-6.2-4.5-4.4 6.2-.9L12 3Z"/>, case: <><rect x="4" y="7" width="16" height="13" rx="2"/><path d="M9 7V5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2M4 12h16M10 12v2h4v-2"/></>, help: <><circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.6 2.6 0 1 1 4.5 1.8c-1.3 1.2-2 1.7-2 3.2M12 17.5v.1"/></>, shield: <><path d="M12 3 19 6v5c0 4.5-3 7.8-7 10-4-2.2-7-5.5-7-10V6l7-3Z"/><path d="m9 12 2 2 4-4"/></>, document: <><path d="M6 3h8l4 4v14H6zM14 3v5h5M9 12h6M9 16h6"/></>, settings: <><circle cx="12" cy="12" r="3"/><path d="m19 13 2 1-2 3-2-1a7 7 0 0 1-2 1l-.5 2h-3L11 17a7 7 0 0 1-2-1l-2 1-2-3 2-1a7 7 0 0 1 0-2l-2-1 2-3 2 1a7 7 0 0 1 2-1l.5-2h3L15 7a7 7 0 0 1 2 1l2-1 2 3-2 1a7 7 0 0 1 0 2Z"/></>, info: <><circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/></> }
function E3Icon({ name }: { name: string }) { return <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" className={`e3-icon e3-icon-${name}`} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{iconShape[name] ?? iconShape.info}</svg> }
export function EmployerAccountHome({ profile, unreadCount, onNavigate }: { profile: EmployerDemoProfile; unreadCount: number; onNavigate: (destination: Destination) => void }) {
  return <main className="employer-page-content e3-account-home"><p className="employer-demo-label">● DEMO · NON-PRODUCTION</p><section className="e3-profile-hero"><span className="e3-avatar">{profile.displayName.trim().split(/\s+/).slice(-2).map((s) => s[0]).join('').toUpperCase()}</span><div><small>{profile.kind === 'individual' ? 'Người thuê cá nhân' : profile.kind === 'shop' ? 'Cửa hàng' : 'Doanh nghiệp'} · DEMO</small><h1>Tài khoản</h1><strong className="e3-profile-name">{profile.displayName}</strong>{profile.businessLabel && <p>{profile.businessLabel}</p>}</div><button type="button" onClick={() => onNavigate('employerProfileEdit')}>Sửa</button></section>
    <div className="e3-shortcuts"><button onClick={() => onNavigate('history')}><b><E3Icon name="list" /></b><span>Yêu cầu<br/>của tôi</span></button><button onClick={() => onNavigate('employerReviews')}><b><E3Icon name="star" /></b><span>Đánh giá<br/>của tôi</span></button><button onClick={() => onNavigate('employerCases')}><b><E3Icon name="case" /></b><span>Phản ánh<br/>của tôi</span></button></div>
    {sections.map((section) => <section className="e3-account-section" key={section.title}><h2>{section.title}</h2><div className="e3-menu-card">{section.items.map((item) => <button key={item.label} onClick={() => onNavigate(item.destination)}><span className="e3-menu-icon"><E3Icon name={item.icon}/></span><span className="e3-menu-copy"><strong>{item.label}{item.destination === 'employerNotifications' && unreadCount > 0 && <i>{unreadCount}</i>}</strong><small>{item.note}</small></span><b aria-hidden="true">›</b></button>)}</div></section>)}
    <p className="e3-disclaimer">Thông tin tài khoản là dữ liệu giả lập, chỉ lưu trong phiên hiện tại.</p></main>
}
