import { useState } from 'react'
import type { EmployerCompletionDecision, EmployerDisputeCase, EmployerIncident, EmployerReview } from '../../types/employerCompletion'
import type { EmployerWorkRequest } from '../../types/domain'
import { getEmployerAssignmentView, getEmployerShiftTracking } from '../../mocks/employerLifecycleFixtures'
import { employerDisputeFixtures, employerIncidentFixtures } from '../../mocks/employerCompletionFixtures'

const categoryLabels = { late_arrival: 'Đến trễ', no_show: 'Không đến', quality: 'Chất lượng dịch vụ', scope: 'Phạm vi công việc', time: 'Sai lệch thời gian', property: 'Tài sản', other: 'Khác' }
const disputeLabels = { submitted: 'Đã gửi demo', under_review: 'Đang xem xét · fixture', needs_information: 'Cần thêm thông tin · fixture', resolved_demo: 'Đã xử lý · demo fixture', closed_demo: 'Đã đóng · demo fixture' }
export function EmployerE2Screen({ screen, request, completion, onCompletion, reviews, onReview, incidents, onIncident, disputes, onDispute, onBack, onOpenReview }: { screen: 'completion' | 'review' | 'incident' | 'dispute'; request?: EmployerWorkRequest; completion?: EmployerCompletionDecision; onCompletion: (value: EmployerCompletionDecision) => void; reviews: EmployerReview[]; onReview: (value: EmployerReview) => void; incidents: EmployerIncident[]; onIncident: (value: EmployerIncident, dispute: EmployerDisputeCase) => void; disputes: EmployerDisputeCase[]; onDispute: (value: EmployerDisputeCase) => void; onBack: () => void; onOpenReview: () => void }) {
  const [stars, setStars] = useState(5); const [tags, setTags] = useState<string[]>([]); const [feedback, setFeedback] = useState(''); const [category, setCategory] = useState<keyof typeof categoryLabels>('quality'); const [description, setDescription] = useState(''); const [evidence, setEvidence] = useState(false)
  const assignment = request ? getEmployerAssignmentView(request.id) : undefined; const shift = request ? getEmployerShiftTracking(request.id) : undefined
  const eligibleCompletion = Boolean(request && assignment?.status === 'active' && shift?.shiftStatus === 'pending_confirmation')
  const savedReview = reviews.find((item) => item.requestId === request?.id && item.assignmentId === assignment?.assignmentId)
  const caseList = [...disputes, ...employerDisputeFixtures]
  function chooseDecision(status: 'confirmed_demo' | 'issue_reported_demo') { if (!request || !assignment || !shift || completion) return; onCompletion({ id: `JF-COMPLETION-${request.id}-${status}`, requestId: request.id, assignmentId: assignment.assignmentId, shiftId: shift.shiftId, status, decidedAt: '2026-10-10T18:10:00+07:00', note: status === 'confirmed_demo' ? 'Employer xác nhận hoàn tất trong phiên demo.' : 'Employer ghi nhận cần hỗ trợ thêm trong phiên demo.' }) }
  const base = <button className="e2-back" type="button" onClick={onBack}>‹ Quay lại chi tiết</button>
  if (screen === 'completion') return <main className="e2-screen">{base}<p className="e2-kicker">E20–E22 · DEMO</p><h1>Tóm tắt hoàn tất</h1>{!request || !assignment || !shift ? <section className="e2-card"><h2>Không có liên kết hợp lệ</h2><p>Chọn yêu cầu có assignment được liên kết.</p></section> : <><section className="e2-card"><h2>{request.serviceLabel}</h2><dl><div><dt>Request</dt><dd>{request.id}</dd></div><div><dt>Assignment</dt><dd>{assignment.assignmentId}</dd></div><div><dt>Người làm demo</dt><dd>{assignment.displayName}</dd></div><div><dt>Ca theo lịch</dt><dd>{assignment.shiftSchedule}</dd></div><div><dt>Sự kiện gần nhất</dt><dd>{shift.events.at(-1)?.label}</dd></div><div><dt>Ngân sách tham khảo</dt><dd>{new Intl.NumberFormat('vi-VN').format(request.referenceBudget)} ₫</dd></div></dl><p>Không tính khoản gia hạn vào quyết toán; không có thanh toán hoặc earnings.</p></section>{completion ? <section className="e2-state" role="status"><strong>{completion.status === 'confirmed_demo' ? 'Đã xác nhận hoàn tất demo' : 'Đã ghi nhận báo vấn đề demo'}</strong><p>{completion.note}</p><small>{completion.id}</small></section> : eligibleCompletion ? <section className="e2-card"><h2>Quyết định của người thuê</h2><p>Fixture này đang chờ xác nhận. Quyết định chỉ cập nhật cục bộ cho yêu cầu này.</p><button className="e2-primary" onClick={() => chooseDecision('confirmed_demo')}>Xác nhận hoàn tất demo</button><button className="e2-secondary" onClick={() => chooseDecision('issue_reported_demo')}>Báo có vấn đề demo</button></section> : <section className="e2-state"><strong>Chưa thể xác nhận</strong><p>Chỉ fixture ca đang chờ xác nhận mới đủ điều kiện.</p></section>}{completion?.status === 'confirmed_demo' && <button className="e2-secondary" onClick={onOpenReview}>Tiếp tục đến đánh giá</button>}</>}</main>
  if (screen === 'review') return <main className="e2-screen">{base}<p className="e2-kicker">E23 · ĐÁNH GIÁ DEMO</p><h1>{savedReview ? 'Đánh giá đã gửi' : 'Đánh giá người làm'}</h1>{!request || !assignment || assignment.status !== 'active' || !['completed', 'awaiting_employer_decision'].includes(request.status) || completion?.status !== 'confirmed_demo' && request.status !== 'completed' ? <section className="e2-state"><strong>Chưa đủ điều kiện đánh giá</strong><p>Cần yêu cầu đã hoàn tất và assignment Worker được liên kết tường minh.</p></section> : savedReview ? <ReviewDetail review={savedReview} workerRating={assignment.rating} /> : <section className="e2-card"><p>Hồ sơ lịch sử fixture: ★ {assignment.rating} · {assignment.completedJobs} việc demo. Đánh giá dưới đây chỉ là bản ghi cục bộ, không đổi rating hồ sơ.</p><fieldset className="e2-stars"><legend>Chọn số sao</legend>{[1,2,3,4,5].map((n) => <button key={n} aria-label={`${n} sao`} aria-pressed={stars === n} onClick={() => setStars(n)}>{n <= stars ? '★' : '☆'}</button>)}</fieldset><div className="e2-tags">{['Đúng giờ','Giao tiếp tốt','Làm việc tốt'].map((tag) => <label key={tag}><input type="checkbox" checked={tags.includes(tag)} onChange={() => setTags((current) => current.includes(tag) ? current.filter((item) => item !== tag) : [...current, tag])}/>{tag}</label>)}</div><label className="e2-field">Nhận xét<textarea value={feedback} maxLength={500} onChange={(event) => setFeedback(event.target.value)} /></label><button className="e2-primary" disabled={reviews.some((item) => item.requestId === request.id && item.assignmentId === assignment.assignmentId)} onClick={() => onReview({ id: `JF-REVIEW-${request.id}-${assignment.assignmentId}`, requestId: request.id, assignmentId: assignment.assignmentId, stars, tags, feedback: feedback.trim(), submittedAt: '2026-10-10T18:12:00+07:00' })}>Gửi đánh giá demo</button><p>DEMO · không cập nhật rating thật và chỉ một đánh giá cho mỗi request/assignment.</p></section>}</main>
  if (screen === 'incident') return <main className="e2-screen">{base}<p className="e2-kicker">E19 · HỖ TRỢ DEMO</p><h1>Báo cáo vấn đề</h1>{!request || !assignment || assignment.status !== 'active' ? <section className="e2-state"><strong>Không có assignment active được liên kết</strong><p>Không thể tạo báo cáo khi chưa có assignment hợp lệ.</p></section> : <section className="e2-card"><p>{request.id} · {assignment.assignmentId}</p><label className="e2-field">Loại vấn đề<select value={category} onChange={(event) => setCategory(event.target.value as keyof typeof categoryLabels)}>{Object.entries(categoryLabels).map(([value,label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="e2-field">Mô tả<textarea value={description} maxLength={1000} onChange={(event) => setDescription(event.target.value)} placeholder="Mô tả trung lập, không nhập thông tin nhạy cảm" /></label><label className="e2-evidence"><input type="checkbox" checked={evidence} onChange={(event) => setEvidence(event.target.checked)}/> Có tệp đính kèm demo</label>{evidence && <div className="e2-state">Tệp minh họa: evidence-demo.png · metadata-only, không chọn hoặc tải file.</div>}<button disabled={description.trim().length < 10} className="e2-primary" onClick={() => { const sequence = incidents.filter((item) => item.requestId === request.id && item.assignmentId === assignment.assignmentId).length + 1; const id = `JF-INCIDENT-${request.id}-${String(sequence).padStart(2,'0')}`; const disputeId = `JF-DISPUTE-${request.id}-${String(sequence).padStart(2,'0')}`; onIncident({ id, disputeId, requestId: request.id, assignmentId: assignment.assignmentId, category, description: description.trim(), evidenceLabel: evidence ? 'evidence-demo.png · metadata only' : 'Không có tệp', submittedAt: '2026-10-10T18:15:00+07:00' }, { id: disputeId, incidentId: id, requestId: request.id, assignmentId: assignment.assignmentId, status: 'submitted', submittedAt: '2026-10-10T18:15:00+07:00', timeline: [{ label: 'Báo cáo demo đã gửi', occurredAt: '2026-10-10T18:15:00+07:00' }] }) }}>Gửi báo cáo demo</button><p>Không tải tài liệu thật. Không có phân xử, bồi thường hoặc quyết định thanh toán.</p></section>}{incidents.filter((item) => item.requestId === request?.id).map((item) => <button className="e2-secondary" key={item.id} onClick={() => onBack()}>Đã gửi {item.id} · xem hỗ trợ</button>)}</main>
  const selectedCase = caseList.find((item) => item.requestId === request?.id)
  const incident = [...incidents, ...employerIncidentFixtures].find((item) => item.id === selectedCase?.incidentId)
  return <main className="e2-screen">{base}<p className="e2-kicker">E24–E26 · CASE DEMO</p><h1>Hồ sơ hỗ trợ</h1>{selectedCase ? <><section className="e2-card"><span className="e2-status">{disputeLabels[selectedCase.status]}</span><h2>{selectedCase.id}</h2><p>Request {selectedCase.requestId} · assignment {selectedCase.assignmentId}</p>{incident && <div><strong>{categoryLabels[incident.category]}</strong><p>{incident.description}</p><small>{incident.evidenceLabel}</small></div>}<ol className="e2-timeline">{selectedCase.timeline.map((event) => <li key={`${event.label}-${event.occurredAt}`}><strong>{event.label}</strong><time>{event.occurredAt}</time></li>)}</ol><p>Hỗ trợ tiếp theo: xem lại thông tin đã gửi trong demo. Không có phán quyết, bồi thường, hoàn tiền hoặc phạt tài khoản.</p></section>{['submitted','under_review','needs_information','resolved_demo','closed_demo'].map((status) => <button className="e2-secondary" key={status} onClick={() => onDispute({ ...selectedCase, status: status as EmployerDisputeCase['status'] })}>Fixture trạng thái: {disputeLabels[status as keyof typeof disputeLabels]}</button>)}</> : <section className="e2-state"><strong>Chưa có hồ sơ cho yêu cầu này</strong><p>Gửi báo cáo demo để tạo case submitted; các trạng thái khác chỉ được chọn từ fixture điều khiển.</p><button onClick={onBack}>Quay lại báo cáo vấn đề</button></section>}</main>
}
function ReviewDetail({ review, workerRating }: { review: EmployerReview; workerRating: string }) { return <section className="e2-card"><strong>{'★'.repeat(review.stars)}{'☆'.repeat(5-review.stars)}</strong><p>{review.feedback || 'Không có nhận xét văn bản.'}</p><p>{review.tags.join(' · ')}</p><small>Hồ sơ rating fixture vẫn là {workerRating} · review local {review.id} · {review.submittedAt}</small></section> }
