import { useState } from 'react'
import type { ReactNode } from 'react'
import type { EmployerDemoProfile, EmployerNotification, EmployerSavedAddress } from '../../types/employerAccount'
import type { EmployerDisputeCase, EmployerIncident, EmployerReview } from '../../types/employerCompletion'
import type { EmployerWorkRequest, Destination } from '../../types/domain'
import { employerHelpArticles } from '../../mocks/employerAccountFixtures'
import { validateEmployerAddress, validateEmployerProfile } from '../../mocks/employerAccountAdapter'
import { employerAssignmentViews } from '../../mocks/employerLifecycleFixtures'

const Page = ({ title, back, children }: { title: string; back: () => void; children: ReactNode }) => <main className="employer-page-content e3-screen"><button className="back-link" onClick={back}>‹ Tài khoản</button><p className="section-kicker">DEMO · NON-PRODUCTION</p><h1>{title}</h1>{children}</main>
export function EmployerProfileEditor({ profile, onSave, onBack }: { profile: EmployerDemoProfile; onSave: (value: EmployerDemoProfile) => void; onBack: () => void }) {
  const [form, setForm] = useState(profile); const [error, setError] = useState('')
  return <Page title="Hồ sơ cá nhân" back={onBack}><section className="e3-card"><label className="form-field">Tên hiển thị<input maxLength={40} value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })}/></label><label className="form-field">Loại người thuê<select value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value as EmployerDemoProfile['kind'] })}><option value="individual">Cá nhân</option><option value="shop">Cửa hàng</option><option value="business">Doanh nghiệp</option></select></label><label className="form-field">Tên hiển thị đơn vị (tuỳ chọn)<input maxLength={50} value={form.businessLabel} onChange={(e) => setForm({ ...form, businessLabel: e.target.value })}/></label>{error && <p role="alert">{error}</p>}<div className="e3-actions"><button onClick={onBack}>Huỷ</button><button className="e3-primary" onClick={() => { const issue = validateEmployerProfile(form); if (issue) setError(issue); else onSave({ ...form, displayName: form.displayName.trim(), businessLabel: form.businessLabel.trim() }) }}>Lưu trong phiên demo</button></div><small>Không thu thập số điện thoại, giấy tờ định danh hoặc dữ liệu tài chính.</small></section></Page>
}
export function EmployerAddresses({ addresses, defaultId, onSave, onDelete, onDefault, onChoose, onBack }: { addresses: EmployerSavedAddress[]; defaultId?: string; onSave: (a: EmployerSavedAddress) => void; onDelete: (id: string) => void; onDefault: (id: string) => void; onChoose: (address: EmployerSavedAddress) => void; onBack: () => void }) {
  const [editing, setEditing] = useState<EmployerSavedAddress | null>(null); const [error, setError] = useState('')
  const start = (item?: EmployerSavedAddress) => { setEditing(item ? { ...item } : { id: '', label: '', kind: 'home', area: '' }); setError('') }
  return <Page title="Địa chỉ của tôi" back={onBack}><button className="e3-primary" onClick={() => start()}>＋ Thêm địa chỉ demo</button>
    {editing && <section className="e3-card" aria-label="Biểu mẫu địa chỉ"><h2>{editing.id ? 'Sửa địa chỉ' : 'Địa chỉ mới'}</h2><label className="form-field">Tên địa chỉ<input maxLength={40} value={editing.label} onChange={(e) => setEditing({ ...editing, label: e.target.value })}/></label><label className="form-field">Loại địa chỉ<select value={editing.kind} onChange={(e) => setEditing({ ...editing, kind: e.target.value as EmployerSavedAddress['kind'] })}><option value="home">Nhà</option><option value="store">Cửa hàng</option><option value="office">Văn phòng</option><option value="other">Khác</option></select></label><label className="form-field">Khu vực / mô tả địa điểm<input maxLength={120} value={editing.area} onChange={(e) => setEditing({ ...editing, area: e.target.value })}/></label>{error && <p role="alert">{error}</p>}<div className="e3-actions"><button onClick={() => setEditing(null)}>Huỷ</button><button className="e3-primary" onClick={() => { const issue = validateEmployerAddress(editing); if (issue) return setError(issue); onSave({ ...editing, id: editing.id || '' }); setEditing(null) }}>Lưu</button></div></section>}
    {addresses.length ? addresses.map((item) => <article className="e3-card e3-address" key={item.id}><div><strong>{item.label} {item.id === defaultId && <i>Mặc định</i>}</strong><p>{item.area}</p><small>{({ home: 'Nhà', store: 'Cửa hàng', office: 'Văn phòng', other: 'Khác' })[item.kind]}</small></div><div className="e3-actions"><button onClick={() => onChoose(item)}>Dùng cho bản nháp</button><button onClick={() => start(item)}>Sửa</button><button onClick={() => { if (window.confirm(`Xoá địa chỉ “${item.label}” khỏi phiên demo?`)) onDelete(item.id) }}>Xoá</button>{item.id !== defaultId && <button onClick={() => onDefault(item.id)}>Đặt mặc định</button>}</div></article>) : <section className="e3-empty">Chưa có địa chỉ demo. Thêm địa chỉ mô phỏng để dùng trong bản nháp.</section>}
    <p className="e3-disclaimer">Địa chỉ giả lập, không dùng GPS hoặc dịch vụ bản đồ.</p></Page>
}
export function EmployerRebook({ requests, onRebook, onOpen, onBack }: { requests: EmployerWorkRequest[]; onRebook: (request: EmployerWorkRequest) => void; onOpen: (id: string) => void; onBack: () => void }) { const eligible = requests.filter((r) => r.status === 'completed' || r.status === 'cancelled'); return <Page title="Đặt lại dịch vụ" back={onBack}>{eligible.length ? eligible.map((r) => <article className="e3-card" key={r.id}><strong>{r.serviceLabel}</strong><p>{r.details}</p><small>{r.id} · {r.location}</small><div className="e3-actions"><button onClick={() => onOpen(r.id)}>Chi tiết cũ</button><button className="e3-primary" onClick={() => onRebook(r)}>Tạo bản nháp mới</button></div></article>) : <div className="e3-empty">Chưa có yêu cầu phù hợp để đặt lại.</div>}<p className="e3-disclaimer">Ngày, giờ và ngân sách cần được xem lại. Không sao chép Worker, assignment, chat, gia hạn, review hoặc case; không tự matching.</p></Page> }
export function EmployerNotifications({ items, onRead, onReadAll, onOpenRequest, onBack }: { items: EmployerNotification[]; onRead: (id: string) => void; onReadAll: () => void; onOpenRequest: (id: string) => void; onBack: () => void }) { const [state, setState] = useState<'success'|'empty'|'error'>('success'); return <Page title="Thông báo" back={onBack}><label className="form-field">Tình huống thông báo demo<select aria-label="Tình huống thông báo demo" value={state} onChange={(e) => setState(e.target.value as typeof state)}><option value="success">Có dữ liệu</option><option value="empty">Rỗng</option><option value="error">Lỗi demo</option></select></label><button onClick={onReadAll} disabled={!items.some((n) => !n.read)}>Đánh dấu tất cả đã đọc</button>{state === 'error' ? <div className="e3-empty" role="status">Không thể tải fixture thông báo demo.</div> : state === 'empty' || !items.length ? <div className="e3-empty" role="status">Chưa có thông báo demo.</div> : items.map((n) => <button className={`e3-card e3-notification${n.read ? '' : ' is-unread'}`} key={n.id} onClick={() => { onRead(n.id); if (n.requestId) onOpenRequest(n.requestId) }}><strong>{n.title}</strong><p>{n.detail}</p><small>{n.requestId ?? 'Thông tin chung'} · {n.createdAt} {n.read ? '· Đã đọc' : '· Chưa đọc'}</small></button>)}<p className="e3-disclaimer">Thông báo cố định, không có push hoặc cập nhật thời gian thực.</p></Page> }
export function EmployerReviewHistory({ reviews, requests, onBack }: { reviews: EmployerReview[]; requests: EmployerWorkRequest[]; onBack: () => void }) { return <Page title="Đánh giá của tôi" back={onBack}>{reviews.length ? reviews.map((r) => { const req = requests.find((x) => x.id === r.requestId); const worker = employerAssignmentViews.find((x) => x.requestId === r.requestId && x.assignmentId === r.assignmentId); return req && worker ? <article className="e3-card" key={r.id}><strong>{req.serviceLabel} · {'★'.repeat(r.stars)}{'☆'.repeat(5-r.stars)}</strong><p>{r.feedback || 'Không có nhận xét.'}</p><small>{r.requestId} · {worker.displayName} · {r.tags.join(' · ')}</small><small>{r.id}</small><time>{r.submittedAt}</time></article> : null }) : <div className="e3-empty">Chưa có đánh giá demo được gửi.</div>}<p className="e3-disclaimer">Đánh giá chỉ đọc; không thay đổi rating lịch sử của Worker.</p></Page> }
export function EmployerCaseHistory({ incidents, disputes, requests, onOpen, onBack }: { incidents: EmployerIncident[]; disputes: EmployerDisputeCase[]; requests: EmployerWorkRequest[]; onOpen: (id: string) => void; onBack: () => void }) { const allI = [...incidents]; const allD = [...disputes]; const category: Record<EmployerIncident['category'], string> = { late_arrival: 'Đến trễ', no_show: 'Không đến', quality: 'Chất lượng dịch vụ', scope: 'Phạm vi công việc', time: 'Sai khác thời gian', property: 'Tài sản', other: 'Khác' }; return <Page title="Phản ánh của tôi" back={onBack}>{allD.length ? allD.map((d) => { const i = allI.find((x) => x.id === d.incidentId && x.requestId === d.requestId && x.assignmentId === d.assignmentId && x.disputeId === d.id); const request = requests.find((x) => x.id === d.requestId); return i && request ? <button className="e3-card e3-case-row" key={d.id} onClick={() => onOpen(d.id)}><strong>{category[i.category]} · {d.id}</strong><p>{request.serviceLabel} · {d.requestId}</p><small>{d.status} · {i.submittedAt}</small></button> : null }) : <div className="e3-empty">Chưa có hồ sơ phản ánh demo.</div>}</Page> }
export function EmployerCaseDetail({ caseId, incidents, disputes, onBack }: { caseId?: string; incidents: EmployerIncident[]; disputes: EmployerDisputeCase[]; onBack: () => void }) { const d = disputes.find((x) => x.id === caseId); const i = d && incidents.find((x) => x.id === d.incidentId && x.disputeId === d.id && x.requestId === d.requestId && x.assignmentId === d.assignmentId); return <Page title="Chi tiết hồ sơ" back={onBack}>{d && i ? <section className="e3-card"><strong>{d.id} · {d.status}</strong><p>{i.category}: {i.description}</p><small>{d.requestId} · {d.assignmentId} · {i.evidenceLabel}</small><ol>{d.timeline.map((t) => <li key={t.occurredAt}>{t.label} · {t.occurredAt}</li>)}</ol><p>Trạng thái chỉ là demo; không có phân xử, bồi thường, hoàn tiền hoặc phạt.</p></section> : <div className="e3-empty">Không tìm thấy hồ sơ khớp đầy đủ. Quay lại danh sách để chọn case cụ thể.</div>}</Page> }
export function EmployerSupport({ articleId, onNavigate, onBack }: { articleId?: string; onNavigate: (d: Destination) => void; onBack: () => void }) { const [open, setOpen] = useState(articleId); const article = employerHelpArticles.find((x) => x.id === open); return <Page title={article ? article.title : 'Trung tâm trợ giúp'} back={onBack}>{article ? <section className="e3-card"><p>{article.body}</p><button className="e3-primary" onClick={() => onNavigate(article.destination)}>Mở luồng liên quan</button><button onClick={() => setOpen(undefined)}>Tất cả chủ đề</button></section> : employerHelpArticles.map((x) => <button className="e3-card e3-help-row" key={x.id} onClick={() => setOpen(x.id)}><strong>{x.title}</strong><b>›</b></button>)}<p className="e3-disclaimer">Không có nhân viên hỗ trợ trực tiếp hoặc cam kết thời gian phản hồi.</p></Page> }
export function EmployerInfoScreen({ destination, onBack, preferences, onPreference }: { destination: Destination; onBack: () => void; preferences: { updates: boolean; reminders: boolean }; onPreference: (key: 'updates' | 'reminders', value: boolean) => void }) { const copy: Partial<Record<Destination, [string,string]>> = { employerPaymentsInfo: ['Thanh toán demo','Không nhập thẻ hoặc tài khoản ngân hàng. Không liên kết, nạp tiền hay giao dịch thật.'], employerPrivacy: ['Quyền riêng tư','Thông tin hồ sơ và địa chỉ ở đây là dữ liệu giả lập trong phiên. Không nhập giấy tờ hoặc dữ liệu nhạy cảm.'], employerTerms: ['Điều khoản sử dụng','Đây là màn hình thông tin demo, không thay thế điều khoản dịch vụ chính thức.'], employerAppInfo: ['Thông tin ứng dụng','JobFree Zalo Mini App · Bản giao diện demo · NON-PRODUCTION.'], employerNotificationSettings: ['Cài đặt thông báo','Tuỳ chọn chỉ áp dụng trong phiên demo; không điều khiển push hoặc Zalo OA.'] }; const [title, text] = copy[destination] ?? ['Thông tin demo','Chưa có nội dung.']; return <Page title={title} back={onBack}><section className="e3-card"><p>{text}</p>{destination === 'employerNotificationSettings' && <><label><input type="checkbox" checked={preferences.updates} onChange={(e) => onPreference('updates',e.target.checked)}/> Cập nhật yêu cầu demo</label><label><input type="checkbox" checked={preferences.reminders} onChange={(e) => onPreference('reminders',e.target.checked)}/> Nhắc việc cần xử lý demo</label></>}</section></Page> }
